// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWg3_Xkf7cH2GoLQpKGcRe45IIKtP48zM',
    appId: '1:305874427986:web:051261ba68eb2b8cedff8b',
    messagingSenderId: '305874427986',
    projectId: 'employee-management-app-59610',
    authDomain: 'employee-management-app-59610.firebaseapp.com',
    storageBucket: 'employee-management-app-59610.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYY_YWKkJEI5te9jlnJkrsI4-N6YgISD0',
    appId: '1:305874427986:android:ab424d9ddde0e643edff8b',
    messagingSenderId: '305874427986',
    projectId: 'employee-management-app-59610',
    storageBucket: 'employee-management-app-59610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhF2awZRuQtKxWfzKYzJh1qvUM_25y8ps',
    appId: '1:305874427986:ios:6c6808dbc584d904edff8b',
    messagingSenderId: '305874427986',
    projectId: 'employee-management-app-59610',
    storageBucket: 'employee-management-app-59610.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhF2awZRuQtKxWfzKYzJh1qvUM_25y8ps',
    appId: '1:305874427986:ios:6c6808dbc584d904edff8b',
    messagingSenderId: '305874427986',
    projectId: 'employee-management-app-59610',
    storageBucket: 'employee-management-app-59610.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWg3_Xkf7cH2GoLQpKGcRe45IIKtP48zM',
    appId: '1:305874427986:web:8fdf7e6c2c9d9778edff8b',
    messagingSenderId: '305874427986',
    projectId: 'employee-management-app-59610',
    authDomain: 'employee-management-app-59610.firebaseapp.com',
    storageBucket: 'employee-management-app-59610.firebasestorage.app',
  );
}
